server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdatabase
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: user-authentication-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: rsmule7777@gmail.com
    password: rgtpkjotaszvolvh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKSA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true

