server:
  port: 8082
  error:
    include-messages: always
spring:
  data:
    mongodb:
      database: userdatabase
      uri: mongodb://localhost:27017
  application:
    name: movie-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKSA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true